### ISSUE TITLE
The pancakes are not in the middle 🥞

### ISSUE THREAD

**Issue by goodjack** [gnehs/made-with-pancake-badge#1]
```
[![Flat](https://gnehs.github.io/made-with-pancake-badge/flat.svg)](https://pancake.tw/)
[![Flat Square](https://gnehs.github.io/made-with-pancake-badge/flat-square.svg)](https://pancake.tw/)
[![For the Badge](https://gnehs.github.io/made-with-pancake-badge/for-the-badge.svg)](https://pancake.tw/)
[![Plastic](https://gnehs.github.io/made-with-pancake-badge/plastic.svg)](https://pancake.tw/)
[![Social](https://gnehs.github.io/made-with-pancake-badge/social.svg)](https://pancake.tw/)
```

## Chrome Dev

Version 108.0.5359.10 (Official Build) dev (x86_64)

### w/ external display 1920x1080
![image](https://user-images.githubusercontent.com/1116129/197453171-c527db26-2804-44bb-8335-b0f3de0ee788.png)

### w/ Macbook retina display
<img width="237" alt="image" src="https://user-images.githubusercontent.com/1116129/197452836-b54a7c30-0c92-4084-bf83-bee3d6edcc19.png">

## Firefox Developer Edition
107.0b4

### w/ external display 1920x1080
![image](https://user-images.githubusercontent.com/1116129/197453887-ff6aa892-8b72-4f67-a368-175aa0fecfbf.png)

### w/ Macbook retina display
<img width="237" alt="image" src="https://user-images.githubusercontent.com/1116129/197453939-c02ecab5-e9e9-414b-948d-06856825b4d8.png">

## Safari
Version 15.6.1 (17613.3.9.1.16)

### w/ external display 1920x1080
![image](https://user-images.githubusercontent.com/1116129/197453988-2cfc8dc0-f2c9-432a-a209-c29b234bdc79.png)

### w/ Macbook retina display
<img width="237" alt="image" src="https://user-images.githubusercontent.com/1116129/197454538-5247b12e-b9ed-4251-82ee-8225ba05e738.png">

**Comment by gnehs** [comment]
these badges are generated by [shields](https://github.com/badges/shields)
i dont know how to fix it :(
